#!/bin/bash

if [ $# -ne 2 ]; then
  echo "USAGE: $0 CFILE UNIT_TEST_NAME"
  echo "  Preprocess, and build, a single test in a single C file."
  exit 1
fi

SCRIPT_DIR="$(dirname $0)"
source "$SCRIPT_DIR/config"

CFILE="$1"
UNIT_TEST="$2"

OUT_DIR=$(mktemp -d /tmp/cn-run-unit-test-XXXXXX)
trap "rm -rf $OUT_DIR" EXIT

cat "$CFILE" | $PREPROC --show-unit "$UNIT_TEST" > "$OUT_DIR/$UNIT_TEST.c"

pushd "$OUT_DIR"
$CPP "$UNIT_TEST.c" > "$UNIT_TEST.i"
mv "$UNIT_TEST.i" "$UNIT_TEST.c"
$CN instrument --fail-fast "$UNIT_TEST.c"
$CC -I "$CN_INSTALL/include" -L "$CN_INSTALL" \
  "$UNIT_TEST-exec.c" -lcn -o "$UNIT_TEST"
"./$UNIT_TEST"
popd



