#!/bin/bash

if [ $# -ne 2 ]; then
  echo "USAGE: $0 CFILE FUN_QUALIFIED_MUTANT_NAME"
  echo "  Preprocess, and test a single mutant in a single C file."
  exit 1
fi

SCRIPT_DIR="$(dirname $0)"
source "$SCRIPT_DIR/config"

CFILE="$1"
FUN=$(dirname "$2")
UNIT_TEST=$(basename "$2")

OUT_DIR=$(mktemp -d /tmp/cn-run-mutant-XXXXXX)
trap "rm -rf $OUT_DIR" EXIT

cat "$CFILE" | $PREPROC --show-mutant "$UNIT_TEST" > "$OUT_DIR/$UNIT_TEST.c"

pushd "$OUT_DIR"
$CPP "$UNIT_TEST.c" > "$UNIT_TEST.i"
mv "$UNIT_TEST.i" "$UNIT_TEST.c"
$CN test "$UNIT_TEST.c" --output-dir=. --only="$FUN" --seed=0 > /dev/null
RESULT=$?
popd
exit $RESULT



