return code: 1
[1/3]: f2 -- fail
[2/3]: f1 -- pass
[3/3]: main -- fail
./src/example-archive/c-testsuite/broken/error-proof/00124.err1.c:4:9: error: Undefined behaviour
	return c - b;
	       ~~^~~ 
an exceptional condition occurs during the evaluation of an expression (§6.5#5)
State file: file:///tmp/state__00124.err1.c__f2.html
./src/example-archive/c-testsuite/broken/error-proof/00124.err1.c:22:9: error: function pointer must be provably equal to a defined function:
call_f10.return
	return (*(*p)(0, 2))(2, 2);
	       ^~~~~~~~~~~~~~~~~~~ 
