return code: 1
[1/3]: Trip -- fail
[2/3]: Generate_Sensor_Trips -- pass
[3/3]: Is_Ch_Tripped -- pass
./src/example-archive/open-sut/broken/error-proof/instrumentation_impl.c:22:17: error: Pointer `setpoints` needs allocation ID
        return (setpoints[ch] < vals[ch]);
                ^~~~~~~~~~~~~ 
(UB missing short message): UB_CERB004_unspecified__pointer_add
State file: file:///tmp/state__instrumentation_impl.c__Trip.html
