return code: 1
[1/1]: main -- fail
./src/example-archive/c-testsuite/broken/error-timeout/00143.timeout.c:14:5: error: Missing resource for loop
    for(n = 0; n < 39; n++) {
    ^~~~~~~~~~~~~~~~~~~~~~~~~ 
Resource needed: Owned<signed int>(&count)
      ./src/example-archive/c-testsuite/broken/error-timeout/00143.timeout.c:14:5: (arg O_count1)
State file: file:///tmp/state__00143.timeout.c__main.html
