# This is a basic workflow to help you get started with Actions

name: Basic CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  run-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
      - name: Prove MPS Components
        uses: addnab/docker-run-action@v3
        with:
          # TODO: replace this with an official cerberus docker image!
          image: podhrmic/cerberus:release
          options: -v ${{ github.workspace }}:/data
          # This action seems to override the docker image entrypoint, as a result
          # we need to run "eval `opam env`" first
          # Use `>` so newlines will be replaced with spaces
          run: >
            eval `opam env` &&
            ./check.sh
